// Local Edit Mode can save directly back to this file in development.
// The edit panel can also copy the current JSON as a manual fallback.
export const authContent = {
  titles: {
    loading: "myBishBash",
    launcher: "Welcome back to myBishBash",
    inviteOnly: "myBishBash is invite-only right now.",
    login: "myBishBash",
    signup: "Create your myBishBash account",
    signupRecovery: "Finish setting up myBishBash",
  },
  copy: {
    loading: "Loading your shared myBishBash...",
    accessDenied: "Get myBishBash with an invite code, join the waitlist, or log in if you already have access.",
    signupBlocked: "Get myBishBash is the invite gate. Enter your access code there first, or join the waitlist.",
    signupRecoveryStandalone: "We couldn’t find your access session. Enter your access code once more to finish creating your account in the app.",
    login: "Log in to sync this shortcut with your myBishBash profile.",
    launcherPrefix: "Log in to continue to your",
    launcherSuffix: "launcher.",
    signup: "Create your account with the access you already unlocked.",
    standalone: "Log in once here to reconnect this Home Screen shortcut.",
  },
  form: {
    email: "Email",
    emailPlaceholder: "you@example.com",
    password: "Password",
    passwordPlaceholder: "Password",
    accessCode: "Access code",
    accessCodePlaceholder: "Enter access code",
    showPassword: "Show",
    hidePassword: "Hide",
    checkingAccess: "Checking...",
    forgotPassword: "Forgot password?",
    sending: "Sending...",
    loginSubmit: "Log In",
    signupSubmit: "Create Account",
    legalPrefix: "I agree to the",
    terms: "Terms of Use",
    legalMiddle: "and",
    privacy: "Privacy Policy",
    legalSuffix: ".",
  },
  actions: {
    getMyBishBash: "Get myBishBash",
    alreadyHaveAccount: "Already have an account?",
    needAccount: "Need an account?",
    loginSwitch: "Log in",
    signupSwitch: "Sign up",
    continue: "Continue",
    backToBrowserSetup: "Back to browser setup",
    noInvite: "No invite yet?",
    joinWaitlist: "Join waitlist",
  },
  status: {
    passwordResetSent: "Password reset email sent. Check your inbox for the link to return to myBishBash.",
    passwordResetError: "Could not send a password reset email.",
    legalRequired: "Please agree to the Terms of Use and Privacy Policy to continue.",
    recoveryInvalid: "That access code didn’t work. Please check it and try again.",
  },
};
