// Local Edit Mode can save directly back to this file in development.
// The edit panel can also copy the current JSON as a manual fallback.
export const onboardingContent = {
  brand: "MyBishBash",
  common: {
    back: "Back",
    continue: "Continue",
    next: "Next",
  },
  steps: {
    learn: {
      title: "Before your apps open",
      body: "MyBishBash shows the Personal Cards you chose before selected apps open.",
      primary: "Create your first card",
      secondary: "Skip Personal Cards for now",
    },
    priority: {
      title: "What would you like more of in your life?",
      body: "Choose a few. We’ll suggest Personal Cards to help keep them front of mind.",
      primary: "Continue",
      secondary: "Skip Personal Cards for now",
      selectedLabel: "selected",
    },
    intention: {
      title: "Build your first Personal Cards",
      body: "These are small reminders you choose for yourself. Pick the ones that fit, or write your own.",
      primary: "Continue",
      secondary: "Skip Personal Cards for now",
      selectedLabel: "selected",
      limitMessage: "You can choose up to five.",
      deselectMessage: "Deselect one card first.",
      writeOwn: "Write my own",
      customPlaceholder: "Write your own reminder…",
      addCustom: "Add",
    },
    commitmentIntro: {
      title: "Remembering is one thing. Following through is another.",
      primary: "Show me",
      secondary: "Skip Commitment Cards for now",
      copy: [
        "Personal Cards help you remember.",
        "Commitment Cards help you follow through.",
        "You can create Commitment Cards later from Home."
      ],
    },
    commitmentTime: {
      label: "Later that day...",
      body: "MyBishBash checks how it went.",
      next: "Next",
    },
    commitmentComplete: {
      title: "You can create Commitment Cards later from Home.",
      body: "Personal Cards help you remember. Commitment Cards help you follow through.",
      primary: "Continue",
    },
    protectedApp: {
      title: "Where should your cards appear first?",
      body: "Choose one app you open regularly.",
      primary: "Continue",
      secondary: "Choose an app later",
      ariaLabel: "Choose your first app",
    },
    protectedDemo: {
      titlePrefix: "Before",
      bodyPrefix: "App Prompts are optional. They add an extra pause before",
      bodySuffix: "opens.",
      primaryPrefix: "Install",
      primarySuffix: "Launcher",
      secondary: "Choose an app later",
      note: "This is an example of an optional App Prompt.",
      toggleLabel: "App Prompts",
      on: "On",
      off: "Off",
      later: "You can change this later.",
      continuePrefix: "Continue to",
      notNow: "Not now",
    },
    protectedSetup: {
      confirmedSuffix: "Launcher Ready",
      installPrefix: "Install",
      installSuffix: "Launcher",
      confirmedBodySuffix: "is now ready to use with MyBishBash.",
      installBodyPrefix: "See your Personal Cards before opening",
      installBodySuffix: ".",
      continueHome: "Continue to Home",
      saved: "I’ve saved it",
      addPrefix: "Add",
      addSuffix: "Launcher",
      secondary: "Choose an app later",
      markedSaved: "Marked as saved",
      homeScreenLauncher: "Home Screen launcher",
      launcherReadySuffix: "launcher ready",
      moveLauncherPrefix: "Move the MyBishBash",
      moveLauncherMiddle: "launcher to where",
      moveLauncherSuffix: "normally sits on your Home Screen. Put the original {appName} app in a folder so you open MyBishBash first.",
      addLauncherPrefix: "Add the",
      addLauncherSuffix: "launcher to your Home Screen.",
      returnNote: "Once it is saved, return to MyBishBash to continue.",
      steps: [
        "Tap Add {appName} Launcher.",
        "Tap Share.",
        "Tap Add to Home Screen.",
        "Keep the suggested name.",
        "Return to MyBishBash to continue."
      ],
    },
    skip: {
      title: "You can set up your first card later.",
      body: "Personal Cards live in MyBishBash. When you are ready, create one reminder and let your phone bring you back to what matters.",
      primary: "Go to Home",
    },
  },
  tutorialDemo: {
    instagram: "Instagram",
    whatsapp: "WhatsApp",
    safari: "Safari",
    openingInstagram: "Opening Instagram",
    openingWhatsApp: "Opening WhatsApp",
    vitaminTitle: "Have you taken your vitamins today?",
    vitaminBody: "A gentle nudge from the version of you that cares.",
    sunscreenTitle: "Have you put your sunscreen on today?",
    sunscreenBody: "A small reminder before the next thing takes over.",
    done: "Done",
    doNow: "I’ll do it now",
    notDone: "Not done",
    ready: "Ready",
    continueInstagram: "Continue to Instagram",
    continueWhatsApp: "Continue to WhatsApp",
    instagramOpens: "Instagram opens",
    whatsappOpens: "WhatsApp opens",
    finalLine: "For the things you genuinely mean to do.",
    replay: "Replay",
  },
  demoCard: {
    kicker: "Personal Card",
    body: "A gentle interruption before the next automatic moment.",
    done: "Done",
    doNow: "I’ll do it now",
    notDone: "Not done",
    words: "Your words",
  },
  personalPreview: {
    label: "Personal Card",
    when: "When",
    where: "Where",
  },
  done: {
    primary: "Open shortcut",
  },
};
